### ISSUE TITLE
setup?

### ISSUE THREAD

**Issue by scorpio2k2** [morgajel/icingaweb2-module-boxydash#1]
0 /usr/share/php/Icinga/Application/Modules/Module.php(503): Icinga\Application\ApplicationBootstrap->Icinga\Application{closure}(8, 'Undefined offse...', '/usr/share/php/...', 503, Array)
#1 /usr/share/php/Icinga/Application/Modules/Module.php(467): Icinga\Application\Modules\Module->metadata()
#2 /usr/share/icingaweb2/application/views/scripts/config/module.phtml(9): Icinga\Application\Modules\Module->getDependencies()
#3 /usr/share/php/Icinga/Web/View.php(206): include('/usr/share/icin...')
#4 /usr/share/php/Zend/View/Abstract.php(888): Icinga\Web\View->_run('/usr/share/icin...')
#5 /usr/share/php/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('config/module.p...')
#6 /usr/share/php/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('config/module.p...', NULL)
#7 /usr/share/php/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /usr/share/php/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /usr/share/php/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /usr/share/php/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('moduleAction')
#11 /usr/share/php/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(154): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#15 {main}

**Comment by morgajel** [comment]
... I have no idea what that means.  To be honest my grip on zend is tenuous at best, and most of this is just garbled bits taken from the monitoring module. I can tell you about my setup so that you can compare and contrast.
- I have it installed on CentOS 7 at  /usr/share/icingaweb2/modules/boxydash
- There is a symlink to it from /etc/icingaweb2/enabledModules/
- I have the following Icinga packages installed (I haven't updated in the past few weeks):
  -  icinga2-bin-2.3.5-1.el7.centos.x86_64
  -  icingaweb2-vendor-JShrink-1.0.1-1.el7.centos.noarch
  -  icingaweb2-vendor-Parsedown-1.0.0-1.el7.centos.noarch
  -  icingaweb2-common-2.0.0-3.beta3.el7.centos.noarch
  -  icingacli-2.0.0-3.beta3.el7.centos.noarch
  -  icinga2-common-2.3.5-1.el7.centos.x86_64
  -  icinga2-2.3.5-1.el7.centos.x86_64
  -  icingaweb2-vendor-HTMLPurifier-4.6.0-1.el7.centos.noarch
  -  icingaweb2-vendor-lessphp-0.4.0-1.el7.centos.noarch
  -  icingaweb2-vendor-dompdf-0.6.1-1.el7.centos.noarch
  -  icingaweb2-2.0.0-3.beta3.el7.centos.noarch
  -  icinga2-ido-mysql-2.3.5-1.el7.centos.x86_64
  -  icingaweb2-vendor-Zend-1.12.9-1.el7.centos.noarch

I will try updating to see if that replicates the issue.

**Comment by tbaror** [comment]
Hi i have issue with Ubuntu 14.04.2 on activating module 

Undefined offset: 1

#0 /usr/share/icingaweb2/library/Icinga/Application/Modules/Module.php(503): Icinga\Application\ApplicationBootstrap->Icinga\Application{closure}(8, 'Undefined offse...', '/usr/share/icin...', 503, Array)
#1 /usr/share/icingaweb2/library/Icinga/Application/Modules/Module.php(467): Icinga\Application\Modules\Module->metadata()
#2 zend.view:///usr/share/icingaweb2/application/views/scripts/config/module.phtml(9): Icinga\Application\Modules\Module->getDependencies()
#3 /usr/share/icingaweb2/library/Icinga/Web/View.php(204): include('zend.view:///us...')
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(893): Zend_View_Abstract->render('config/module.p...')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(914): Zend_Controller_Action_Helper_ViewRenderer->renderScript('config/module.p...', NULL)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(953): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch('moduleAction')
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/icingaweb2/library/Icinga/Application/Web.php(154): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#15 {main}

**Comment by morgajel** [comment]
ah, so it's an activation thing. I can attempt to replicate that. I'll report back on what I find.

**Comment by morgajel** [comment]
OK guys, pull the latest version and see how it work for you.

**Comment by sysmike** [comment]
Works for me now, thanks.

**Comment by morgajel** [comment]
@scorpio2k2, @tbaror: how about you?

**Comment by scorpio2k2** [comment]
The first version worked after I created the symlink from /usr/share/icingaweb2/modules/boxydash to /etc/icingaweb2/enabledModules/
![dash](https://cloud.githubusercontent.com/assets/915081/8807617/6944583e-2fe6-11e5-9255-a3b70d56cd36.PNG)

**Comment by morgajel** [comment]
@scorpio2k2 yeah, there was a bug in the module.info and/or the run.php file that probably caused the initial problem.

As an aside, you have no idea how awesome that is  to see (also, the new version makes the legend look a little less sucky).

**Comment by morgajel** [comment]
@scorpio2k2 it's also worth noting that the older version broke icingacli modules list; that should be resolved now.
